# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rowSumsC <- function(x) {
    .Call(`_MFClust_rowSumsC`, x)
}

mat_to_list <- function(m, V, K) {
    .Call(`_MFClust_mat_to_list`, m, V, K)
}

sigma_GKV_func <- function(mu_GK_V_new, std_data, w_NK_V, N, NG, V) {
    .Call(`_MFClust_sigma_GKV_func`, mu_GK_V_new, std_data, w_NK_V, N, NG, V)
}

