# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rowSumsC <- function(x) {
    .Call(`_MFClust_rowSumsC`, x)
}

MarginalLL_v_func <- function(N, NG, K_v, std_data, mu_GK, sigma_Gv, pK) {
    .Call(`_MFClust_MarginalLL_v_func`, N, NG, K_v, std_data, mu_GK, sigma_Gv, pK)
}

ConditionalLL_ls_func <- function(N, NG, V, K, std_data, pVK, mu_GK_V, sigma_GV) {
    .Call(`_MFClust_ConditionalLL_ls_func`, N, NG, V, K, std_data, pVK, mu_GK_V, sigma_GV)
}

mat_to_list <- function(m, V, K) {
    .Call(`_MFClust_mat_to_list`, m, V, K)
}

sigma_GKV_func <- function(mu_GK_V_new, std_data, w_NK_V, N, NG, V) {
    .Call(`_MFClust_sigma_GKV_func`, mu_GK_V_new, std_data, w_NK_V, N, NG, V)
}

